/* eslint-disable no-restricted-globals, import/no-extraneous-dependencies, global-require */
/* global self */

// This is an example of a feature set that could be built using react-scripts and then the output hosted somewhere, for example on S3, as a versioned polyfill bundle

// We add `caniuse: feature-name` 'magic comments' after each require.
// These are 'magic' because we make them so, not because any external build tool requires them. A list of 'feature-names' is generated by our in-repo tooling and passed to `browserslist-useragent-regexp` to generate a regex of all user agents that DO support the given features, based on this package's use of `caniuse-lite`.
// It is therefore critical the names match with `caniuse` feature names. The set of `caniuse` features can be found at https://github.com/Fyrd/caniuse/tree/master/features-json

if (typeof Promise === 'undefined') {
  // Rejection tracking prevents a common issue where React gets into an
  // inconsistent state due to an error, but it gets swallowed by a Promise,
  // and the user has no idea what causes React's erratic future behavior.
  require('promise/lib/rejection-tracking').enable(); // caniuse: promises
  self.Promise = require('promise/lib/es6-extensions.js');
}

// Make sure we're in a Browser-like environment before importing polyfills
// This prevents `fetch()` from being imported in a Node test environment
if (typeof window !== 'undefined') {
  // fetch() polyfill for making API calls.
  require('whatwg-fetch'); // caniuse: fetch
}

// Babel requires these first two, the rest are optional
// https://babeljs.io/docs/en/caveats
require('core-js/features/symbol'); // caniuse: symbols
require('core-js/features/array/from'); // caniuse: es6

require('core-js/features/array/find'); // caniuse: array-find
require('core-js/features/array/find-index'); // caniuse: array-find-index
require('core-js/features/array/includes'); // caniuse: array-includes

require('core-js/features/object/entries'); // caniuse: object-entries
require('core-js/features/object/values'); // caniuse: object-values
require('core-js/features/object/assign'); // caniuse: es6

require('core-js/features/string/includes'); // caniuse: es6-string-includes
require('core-js/features/string/ends-with'); // caniuse: es6
require('core-js/features/string/starts-with'); // caniuse: es6

require('core-js/features/number/is-finite'); // caniuse: es6-number
require('core-js/features/number/is-nan'); // caniuse: es6-number

require('core-js/features/set'); // caniuse: es6
require('core-js/features/map'); // caniuse: es6
require('core-js/features/url'); // caniuse: url
